// Seed content for /impressum and /datenschutz until the admin edits them.
// Uses neutral, portfolio-mode wording so the site can legally stay online
// while the operator fills in the fields via /admin.

export const DEFAULT_LEGAL = {
  impressum: {
    de: `Dies ist ein privates Design-Portfolio.\n\nAuf dieser Seite werden keine Angebote im Sinne von § 145 BGB gemacht. Sämtliche gezeigten Arbeiten dienen ausschließlich der Präsentation.\n\nFür Rückfragen nutzen Sie bitte das Kontaktformular auf der Website — ein Impressum im Sinne von § 5 TMG ist aufgrund des privaten Charakters dieses Portfolios nicht erforderlich. Sobald die Website kommerziell genutzt wird, werden die gesetzlich vorgeschriebenen Angaben hier ergänzt.`,
    en: `This is a private design portfolio.\n\nThe content on this site does not constitute a commercial offer under § 145 BGB. All displayed works are shown for presentation purposes only.\n\nPlease use the contact form on the site for any inquiries. A formal legal notice under § 5 TMG will be added as soon as the site is used commercially.`,
    ru: `Это частное дизайн-портфолио.\n\nМатериалы на сайте не являются коммерческим предложением в смысле § 145 BGB. Все представленные работы опубликованы исключительно в презентационных целях.\n\nПо любым вопросам, пожалуйста, используйте контактную форму на сайте. Полноценный Impressum согласно § 5 TMG будет добавлен, как только сайт начнёт использоваться в коммерческих целях.`,
  },
  datenschutz: {
    de: `Datenschutzerklärung\n\nDieses Portfolio wird auf Vercel (USA/EU) betrieben. Beim Aufruf der Seite werden durch den Hosting-Anbieter temporär Server-Logfiles (IP-Adresse, Zeitstempel, User-Agent) erzeugt und in der Regel nach wenigen Tagen automatisch gelöscht.\n\nWenn Sie das Kontaktformular nutzen, werden die eingegebenen Daten (Name, E-Mail, Betreff, Nachricht) ausschließlich zur Beantwortung Ihrer Anfrage verarbeitet und an den Betreiber per E-Mail (Resend) und Telegram weitergeleitet. Eine Weitergabe an Dritte findet darüber hinaus nicht statt.\n\nSie haben jederzeit das Recht auf Auskunft, Berichtigung, Löschung und Einschränkung der Verarbeitung Ihrer Daten (Art. 15–21 DSGVO) sowie das Recht, sich bei einer Datenschutz-Aufsichtsbehörde zu beschweren.`,
    en: `Privacy Notice\n\nThis portfolio is hosted on Vercel (USA/EU). When you open the site, the hosting provider temporarily creates server log files (IP address, timestamp, user agent) that are automatically removed after a few days.\n\nIf you use the contact form, the data you enter (name, email, subject, message) is processed solely to respond to your inquiry and is forwarded to the operator via email (Resend) and Telegram. No data is shared with any third party beyond that.\n\nUnder the GDPR (Art. 15–21) you have the right to access, correct, delete or restrict the processing of your data at any time, and you may file a complaint with a data protection authority.`,
    ru: `Политика конфиденциальности\n\nСайт размещён на Vercel (США/ЕС). При открытии страницы хостинг-провайдер временно создаёт серверные лог-файлы (IP-адрес, время, user-agent), которые автоматически удаляются через несколько дней.\n\nПри использовании контактной формы введённые вами данные (имя, email, тема, сообщение) обрабатываются исключительно для ответа на ваш запрос и пересылаются владельцу сайта по email (Resend) и в Telegram. Третьим лицам данные не передаются.\n\nСогласно GDPR (ст. 15–21) вы в любой момент имеете право на доступ, исправление, удаление и ограничение обработки ваших данных, а также право подать жалобу в надзорный орган по защите данных.`,
  },
  updatedAt: null,
};
